name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ github.workspace }}
    steps:
      
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: mkdir builds
      run: mkdir builds
      
    - name: go build
      run: |
        GOOS=linux GOARCH=amd64 go build -o builds/torch-linux-amd64 ./src/github.com/${{ github.repository }} && \
        GOOS=linux GOARCH=arm go build -o builds/torch-linux-arm ./src/github.com/${{ github.repository }} && \
        GOOS=darwin GOARCH=amd64 go build -o builds/torch-darwin-amd64 ./src/github.com/${{ github.repository }} && \
        GOOS=freebsd GOARCH=amd64 go build -o builds/torch-freebsd-amd64 ./src/github.com/${{ github.repository }} && \
        GOOS=windows GOARCH=amd64 go build -o builds/torch-windows-amd64.exe ./src/github.com/${{ github.repository }}
      
    
    - uses: actions/upload-artifact@v2
      with:
        name: builds
        path: builds/
        
