name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GOPATH: $PWD 
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: ./src/github.com/${{ github.repository }}
    
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: mkdir builds
      run: mkdir builds
      
    - name: Generate build files
      run: GOOS=linux GOARCH=amd64 go build -o builds/torch-linux-amd64
    
    - uses: actions/upload-artifact@v2
      with:
        name: builds
        path: builds/
        
